/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-04-13 08:41:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.users.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>index</title>\r\n");

	pageContext.setAttribute("APP_PATH", request.getContextPath());
	pageContext.setAttribute("APP_PHONE",request.getSession().getAttribute("loginUser"));

      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/img/favicon.ico\" mce_href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/img/favicon.ico\"  type=\"image/x-icon\" />\r\n");
      out.write("\r\n");
      out.write("<!-- web路径：\r\n");
      out.write("不以/开始的相对路径，找资源，以当前资源的路径为基准，经常容易出问题。\r\n");
      out.write("以/开始的相对路径，找资源，以服务器的路径为标准(http://localhost:3306)；需要加上项目名\r\n");
      out.write("\t\thttp://localhost:3306/crud\r\n");
      out.write(" -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/bootstrap-3.3.7-dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/bootstrap-3.3.7-dist/css/main.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--顶部导航栏部分-->\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<!-- <a class=\"navbar-brand\" title=\"logoTitle\" href=\"#\">logo</a> -->\r\n");
      out.write("\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/img/logo.jpg\" alt=\"\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a>当前用户：</a></li>\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a id=\"epName\"></a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"reback\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-lock\"></span>退出登录\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- 中间主体内容部分 -->\r\n");
      out.write("\t<div class=\"pageContainer\">\r\n");
      out.write("\t\t<!-- 左侧导航栏 -->\r\n");
      out.write("\t\t<div class=\"pageSidebar\">\r\n");
      out.write("\t\t\t<ul class=\"nav nav-stacked nav-pills\">\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a href=\"Employee\" target=\"mainFrame\">员工管理</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a href=\"Car\" target=\"mainFrame\">车辆管理</a></li>\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a href=\"Route\" target=\"mainFrame\">线路管理</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"nav4.html\" target=\"mainFrame\">\r\n");
      out.write("\t\t\t\t\t\t订单管理<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"Orst\" target=\"mainFrame\">订单情况</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"OrderG\" target=\"mainFrame\">订单详细</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li role=\"presentation\"><a href=\"Storehouse\" target=\"mainFrame\">仓库管理</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"nav4.html\" target=\"mainFrame\">\r\n");
      out.write("\t\t\t\t\t\t数据统计<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"DeptCount\" target=\"mainFrame\">部门人数统计</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"St_type_count\" target=\"mainFrame\">仓库统计</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"OrderGCount\" target=\"mainFrame\">订单统计</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"CARCount\" target=\"mainFrame\">车辆统计</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<!-- 开始 -->\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" href=\"nav4.html\" target=\"mainFrame\">\r\n");
      out.write("\t\t\t\t\t\t个人设置<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" id=\"password_update\">修改个人信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"reback\">退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<!-- 结束 -->\r\n");
      out.write("\t\t\t\t<!-- <li role=\"presentation\">\r\n");
      out.write("                 <a href=\"nav5.html\" target=\"mainFrame\">权限设置</a>\r\n");
      out.write("             </li> -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 左侧导航和正文内容的分隔线 -->\r\n");
      out.write("\t\t<div class=\"splitter\"></div>\r\n");
      out.write("\t\t<!-- 正文内容部分 -->\r\n");
      out.write("\t\t<div class=\"pageContent\">\r\n");
      out.write("\t\t\t<iframe src=\"home\" id=\"mainFrame\" name=\"mainFrame\" frameborder=\"0\"\r\n");
      out.write("\t\t\t\twidth=\"100%\" height=\"100%\" frameBorder=\"0\"> </iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 底部页脚部分 -->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<p class=\"text-center\">2020 &copy; LMS物流管理系统.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 员工修改的模态框 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"empUpdateModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">员工修改</h4>\r\n");
      out.write("\t\t\t\t\t<!-- <p class=\"form-control-static\" name=\"UpempId\" id=\"empid_update_static\"></p> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">员工ID：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" readonly=\"readonly\" name=\"empId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"empID_update_static\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"empId\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">姓名：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"empName_update_static\" placeholder=\"empName\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">性别：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"sex\" id=\"gender1_update_input\" value=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tchecked=\"checked\"> 男\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <label class=\"radio-inline\"> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"sex\" id=\"gender2_update_input\" value=\"0\"> 女\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">手机：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"phone\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"phone_update_static\" placeholder=\"phone\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">邮箱：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"email_static\" placeholder=\"email@atguigu.com\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">地址：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"address\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"address_static\" placeholder=\"地址\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">密码：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"password\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"password_update_input\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">部门：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"form-control-static\" id=\"deptName_static\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">职位：</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"form-control-static\" id=\"role_static\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"emp_update_btn\">更新</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar pphone = \"\";\r\n");
      out.write("\t\t\t//1.页面加载完成以后，直接去发送一个ajax请求，要到分页数据\r\n");
      out.write("\t\t\t//console.log('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t\t\tvar epName = \"\";\r\n");
      out.write("\t\t\tfunction parseUrl(url) {\r\n");
      out.write("\t\t\t\tif (url.indexOf(\"?\") == -1) {\r\n");
      out.write("\t\t\t\t\treturn {};\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar query = url.split(\"?\")[1];\r\n");
      out.write("\t\t\t\tvar queryArr = query.split(\"&\");\r\n");
      out.write("\t\t\t\tvar obj = {};\r\n");
      out.write("\t\t\t\tqueryArr.forEach(function(item) {\r\n");
      out.write("\t\t\t\t\tvar key = item.split(\"=\")[0];\r\n");
      out.write("\t\t\t\t\tvar value = item.split(\"=\")[1];\r\n");
      out.write("\t\t\t\t\tobj[key] = decodeURIComponent(value);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\treturn obj;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// url传递的信息\r\n");
      out.write("\t\t\t//var urlMsg = parseUrl(window.location.search);\r\n");
      out.write("\t\t\tconsole.log(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t//url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/emp/\" + urlMsg.phone,\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/emp/\" +\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PHONE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\tvar empData = result.extend.emp;\r\n");
      out.write("\t\t\t\t\tepName = empData.name;\r\n");
      out.write("\t\t\t\t\t$(\"#epName\").text(empData.name);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#password_update\").click(function() {\r\n");
      out.write("\t\t    \tgetEmp(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PHONE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\t\t//4、把员工的id传递给模态框的更新按钮\r\n");
      out.write("\t\t\t\t$(\"#emp_update_btn\").attr(\"edit-phone\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PHONE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\t\t$(\"#empUpdateModal\").modal({\r\n");
      out.write("\t\t\t\t\tbackdrop : \"static\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//显示校验结果的提示信息\r\n");
      out.write("\t\tfunction show_validate_msg(ele, status, msg) {\r\n");
      out.write("\t\t\t//清除当前元素的校验状态\r\n");
      out.write("\t\t\t$(ele).parent().removeClass(\"has-success has-error\");\r\n");
      out.write("\t\t\t$(ele).next(\"span\").text(\"\");\r\n");
      out.write("\t\t\tif (\"success\" == status) {\r\n");
      out.write("\t\t\t\t$(ele).parent().addClass(\"has-success\");\r\n");
      out.write("\t\t\t\t$(ele).next(\"span\").text(msg);\r\n");
      out.write("\t\t\t} else if (\"error\" == status) {\r\n");
      out.write("\t\t\t\t$(ele).parent().addClass(\"has-error\");\r\n");
      out.write("\t\t\t\t$(ele).next(\"span\").text(msg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//个人信息\r\n");
      out.write("\t\tfunction getEmp(phone) {\r\n");
      out.write("\t\t\tconsole.log(phone);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/emp/\" + phone,\r\n");
      out.write("\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tvar empData = result.extend.emp;\r\n");
      out.write("\t\t\t\t\tpphone = empData.phone;\r\n");
      out.write("\t\t\t\t\t$(\"#empID_update_static\").val(empData.empId);\r\n");
      out.write("\t\t\t\t\t$(\"#empName_update_static\").val(empData.name);\r\n");
      out.write("\t\t\t\t\t$(\"#empUpdateModal input[name=sex]\").val([ empData.sex ]);\r\n");
      out.write("\t\t\t\t\t$(\"#email_static\").val(empData.email);\r\n");
      out.write("\t\t\t\t\t$(\"#address_static\").val(empData.address);\r\n");
      out.write("\t\t\t\t\t$(\"#phone_update_static\").val(empData.phone);\r\n");
      out.write("\t\t\t\t\t$(\"#password_update_input\").val(empData.password);\r\n");
      out.write("\t\t\t\t\t$(\"#deptName_static\").text(empData.depId == 1 ? \"运输部\"\r\n");
      out.write("\t\t\t\t\t\t\t: ((empData.depId == 2) ? \"仓库管理\":((empData.depId == 3) ? \"物流派送\":\r\n");
      out.write("\t\t\t\t\t\t\t\t\t((empData.depId == 4) ? \"信息管理\":((empData.depId == 5) ? \"财务部\": \"人事部\")))));\r\n");
      out.write("\t\t\t\t\t$(\"#role_static\").text(empData.role == 1 ? \"非正式员工\"\r\n");
      out.write("\t\t\t\t\t\t\t: ((empData.role == 2) ? \"正式员工\": ((empData.role == 3) ? \"司机\": ((empData.role == 4) ? \"派送员\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t: ((empData.role == 5) ? \"管理员\": \"经理\")))));\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//点击更新，更新员工信息\r\n");
      out.write("\t\t$(\"#emp_update_btn\").click(function() {\r\n");
      out.write("\t\t\t//验证邮箱是否合法\r\n");
      out.write("\t\t\t//1、校验邮箱信息\r\n");
      out.write("\t\t\tvar email = $(\"#email_static\").val();\r\n");
      out.write("\t\t\tvar regEmail = /^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$/;\r\n");
      out.write("\t\t\tif (!regEmail.test(email)) {\r\n");
      out.write("\t\t\t\tshow_validate_msg(\"#email_static\",\"error\", \"邮箱格式不正确\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tshow_validate_msg(\"#email_static\",\"success\", \"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t//2、校验名字信息\r\n");
      out.write("\t\t\tvar empName = $(\"#empName_update_static\").val();\r\n");
      out.write("\t\t\tvar regName = /(^[a-zA-Z0-9_-]{6,16}$)|(^[\\u2E80-\\u9FFF]{2,5})/;\r\n");
      out.write("\t\t\tif (!regName.test(empName)) {\r\n");
      out.write("\t\t\t\t//alert(\"用户名可以是2-5位中文或者6-16位英文和数字的组合\");\r\n");
      out.write("\t\t\t\tshow_validate_msg(\"#empName_update_static\",\"error\", \"用户名可以是2-5位中文或者6-16位英文和数字的组合\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tshow_validate_msg(\"#empName_update_static\",\"success\", \"\");\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t//3、校验手机号信息\r\n");
      out.write("\t\t\tvar phone = $(\"#phone_update_static\").val();\r\n");
      out.write("\t\t\tvar regphone = /^1([38][0-9]|4[579]|5[0-3,5-9]|6[6]|7[0135678]|9[89])\\d{8}$/;\r\n");
      out.write("\t\t\tif (!regphone.test(phone)) {\r\n");
      out.write("\t\t\t\tshow_validate_msg(\"#phone_update_static\",\"error\", \"手机号码格式错误\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tshow_validate_msg(\"#phone_update_static\",\"success\", \"\");\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\tconsole.log($(this).attr(\"edit-phone\"));\r\n");
      out.write("\t\t\t//4、发送ajax请求保存更新的员工数据\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/emp/\"+ $(this).attr(\"edit-phone\"),\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\tdata : $(\"#empUpdateModal form\").serialize()+\"&_method=PUT\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t//alert(result.msg);\r\n");
      out.write("\t\t\t\t\t//1、关闭对话框\r\n");
      out.write("\t\t\t\t\t$(\"#empUpdateModal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t\t//2、回到本页面\r\n");
      out.write("\t\t\t\t\tto_page(currentPage);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
