/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-04-13 08:51:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.users.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>员工登陆</title>\r\n");
      out.write("\r\n");

	pageContext.setAttribute("APP_PATH", request.getContextPath());

      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/img/favicon.ico\" mce_href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/img/favicon.ico\"  type=\"image/x-icon\" />\r\n");
      out.write("\r\n");
      out.write("<!-- web路径：\r\n");
      out.write("不以/开始的相对路径，找资源，以当前资源的路径为基准，经常容易出问题。\r\n");
      out.write("以/开始的相对路径，找资源，以服务器的路径为标准(http://localhost:3306)；需要加上项目名\r\n");
      out.write("\t\thttp://localhost:3306/crud\r\n");
      out.write(" -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"static/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"static/bootstrap-3.3.7-dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"static/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body\r\n");
      out.write("\tstyle=\"background: url(static/img/login.jpg) no-repeat center center fixed; background-size: 100%;\">\r\n");
      out.write("\t<!-- <h3 class=\"modal-title text-center\">13000014229</h3>\r\n");
      out.write("\t<h3 class=\"modal-title text-center\">00000000</h3> -->\r\n");
      out.write("\t<div class=\"modal-dialog\" style=\"margin-top: 10%;\" id=\"loginModal\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title text-center\" id=\"myModalLabel\">登录</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form class=\"form-horizontal\" action=\"login\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"modal-body\" id=\"model-body\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"phone\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tid=\"userphone_input\" placeholder=\"phone\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t<span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" class=\"form-control\" placeholder=\"密码\"\r\n");
      out.write("\t\t\t\t\t\tautocomplete=\"off\" name=\"password\" id=\"password_input\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary form-control\"\r\n");
      out.write("\t\t\t\t\t\tid=\"emp_login_btn\">登录</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.modal-content -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.modal -->\r\n");
      out.write("</body>\r\n");
      out.write("<!-- <script type=\"text/javascript\">\r\n");
      out.write("var pp=\"\";\r\n");
      out.write("//显示校验结果的提示信息\r\n");
      out.write("function show_validate_msg(ele, status, msg) {\r\n");
      out.write("\t//清除当前元素的校验状态\r\n");
      out.write("\t$(ele).parent().removeClass(\"has-success has-error\");\r\n");
      out.write("\t$(ele).next(\"span\").text(\"\");\r\n");
      out.write("\tif (\"success\" == status) {\r\n");
      out.write("\t\t$(ele).parent().addClass(\"has-success\");\r\n");
      out.write("\t\t$(ele).next(\"span\").text(msg);\r\n");
      out.write("\t} else if (\"error\" == status) {\r\n");
      out.write("\t\t$(ele).parent().addClass(\"has-error\");\r\n");
      out.write("\t\t$(ele).next(\"span\").text(msg);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("//校验phone是否可用\r\n");
      out.write("$(\"#userphone_input\").change(\r\n");
      out.write("\t\tfunction() {\r\n");
      out.write("\t\t\t//发送ajax请求校验phone是否可用\r\n");
      out.write("\t\t\tvar phone = this.value;\r\n");
      out.write("\t\t\tpp=phone;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/checkuserPhone\",\r\n");
      out.write("\t\t\t\tdata : \"phone=\" + phone,\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tif (result.code == 100) {\r\n");
      out.write("\t\t\t\t\t\tshow_validate_msg(\"#userphone_input\",\"success\", \"输入正确\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#emp_login_btn\").attr(\"ajax-va\", \"success\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tshow_validate_msg(\"#userphone_input\", \"error\",result.extend.va_msg);\r\n");
      out.write("\t\t\t\t\t\t$(\"#emp_login_btn\").attr(\"ajax-va\", \"error\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("//员工登录\r\n");
      out.write("$(\"#emp_login_btn\").click(function() {\r\n");
      out.write("\t $.ajax({\r\n");
      out.write("\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login\",\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\tdata : $(\"#loginModal form\").serialize(),\r\n");
      out.write("\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t//console.log(request.getSession().getAttribute(\"loginUser\"));\r\n");
      out.write("\t\t\t//登陆跳转\r\n");
      out.write("\t\t\tif(result>3){\r\n");
      out.write("\t\t\t\twindow.location.href =  \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/users/page/index.jsp?phone=\"+pp;\r\n");
      out.write("\t\t\t}else if(result>2){\r\n");
      out.write("\t\t\t\twindow.location.href =  \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/users/page/index2.jsp?phone=\"+pp;\r\n");
      out.write("\t\t\t}else if(result>0){\r\n");
      out.write("\t\t\t\twindow.location.href =  \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/users/page/index3.jsp?phone=\"+pp;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tshow_validate_msg(\"#password_input\", \"error\",\"密码错误！！\");\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t});  \r\n");
      out.write("});\r\n");
      out.write("</script> -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
