/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-04-01 09:04:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.users.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orderG2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>订单列表</title>\r\n");

	pageContext.setAttribute("APP_PATH", request.getContextPath());

      out.write("\r\n");
      out.write("<!-- web路径：\r\n");
      out.write("不以/开始的相对路径，找资源，以当前资源的路径为基准，经常容易出问题。\r\n");
      out.write("以/开始的相对路径，找资源，以服务器的路径为标准(http://localhost:3306)；需要加上项目名\r\n");
      out.write("\t\thttp://localhost:3306/crud\r\n");
      out.write(" -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/bootstrap-3.3.7-dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/js/bootstrap-datetimepicker.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 订单查询 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"orderGcheckModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t<div class=\"modal-dialog  modal-lg\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">订单查询</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body row col-md-12\">\r\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-2 control-label\">订单id:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"ordid\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"ordid_input\" placeholder=\"ordid\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"orderG_check_btn\">查询</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 搭建显示页面 -->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- title -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t<h1>订单信息查看</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 按钮 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-md-offset-9\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary\" id=\"orderG_check_modal_btn\">\r\n");
      out.write("\t\t\t\t<span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span>查找</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 显示表格数据 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 \">\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\" id=\"orderGs_table\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><input type=\"checkbox\" id=\"check_all\" /></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>订单Id</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>寄件人</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>电话</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>地址</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>收件人</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>电话</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>地址</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>备注</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 显示分页信息 -->\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<!--分页文字信息  -->\r\n");
      out.write("\t\t\t<div class=\"col-md-6\" id=\"page_info_area\"></div>\r\n");
      out.write("\t\t\t<!-- 分页条信息 -->\r\n");
      out.write("\t\t\t<div class=\"col-md-6\" id=\"page_nav_area\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$('#date').datetimepicker({\r\n");
      out.write("\t\tforceParse : 0,//设置为0，时间不会跳转1899，会显示当前时间。\r\n");
      out.write("\t\tlanguage : 'zh-CN',//显示中文\r\n");
      out.write("\t\tformat : 'yyyy-mm-dd',//显示格式\r\n");
      out.write("\t\tminView : \"month\",//设置只显示到月份\r\n");
      out.write("\t\tinitialDate : new Date(),//初始化当前日期\r\n");
      out.write("\t\tautoclose : true,//选中自动关闭\r\n");
      out.write("\t\ttodayBtn : true\r\n");
      out.write("\t//显示今日按钮\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#date_update_input').datetimepicker({\r\n");
      out.write("\t\tforceParse : 0,//设置为0，时间不会跳转1899，会显示当前时间。\r\n");
      out.write("\t\tlanguage : 'zh-CN',//显示中文\r\n");
      out.write("\t\tformat : 'yyyy-mm-dd',//显示格式\r\n");
      out.write("\t\tminView : \"month\",//设置只显示到月份\r\n");
      out.write("\t\tinitialDate : new Date(),//初始化当前日期\r\n");
      out.write("\t\tautoclose : true,//选中自动关闭\r\n");
      out.write("\t\ttodayBtn : true\r\n");
      out.write("\t//显示今日按钮\r\n");
      out.write("\t})\r\n");
      out.write("\t$(\"#date\").datetimepicker(\"setDate\", new Date()); //设置显示默认当天的时间\r\n");
      out.write("\t\tvar totalRecord, currentPage;\r\n");
      out.write("\t\t//1.页面加载完成以后，直接去发送一个ajax请求，要到分页数据\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t//去首页\r\n");
      out.write("\t\t\tto_page(1);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction to_page2(orid) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/orderGs/\"+orid,\r\n");
      out.write("\t\t\t\t//data : \"orid=\"+orid,\r\n");
      out.write("\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t//console.log(result);\r\n");
      out.write("\t\t\t\t\t//1.解析并显示订单数据\r\n");
      out.write("\t\t\t\t\tbuild_orderGs_table(result);\r\n");
      out.write("\t\t\t\t\t//2.解析并显示分页信息\r\n");
      out.write("\t\t\t\t\t//build_page_info(result);\r\n");
      out.write("\t\t\t\t\t//3.解析并显示分页条\r\n");
      out.write("\t\t\t\t\t//build_page_nav(result);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//点击\r\n");
      out.write("\t\t$(\"#orderG_check_modal_btn\").click(function() {\r\n");
      out.write("\t\t\t//orderGcheckModal\r\n");
      out.write("\t\t\treset_form(\"#orderGcheckModal form\");\r\n");
      out.write("\t\t\t//发送ajax请求，查出route信息，显示在下拉列表中\r\n");
      out.write("\t\t\t//getRoutets(\"#orstAddModal select\");\r\n");
      out.write("\t\t\t//弹出模态框\r\n");
      out.write("\t\t\t$(\"#orderGcheckModal\").modal({\r\n");
      out.write("\t\t\t\tbackdrop : \"static\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#orderG_check_btn\").click(function() {\r\n");
      out.write("\t\t\tvar orid=$(\"#ordid_input\").val();\r\n");
      out.write("\t\t\tconsole.log(orid);\r\n");
      out.write("\t\t\tto_page2(orid);\r\n");
      out.write("\t\t\t//1、关闭对话框\r\n");
      out.write("\t\t\t$(\"#orderGcheckModal\").modal(\"hide\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction to_page(pn) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/orderGs\",\r\n");
      out.write("\t\t\t\tdata : \"pn=\" + pn,\r\n");
      out.write("\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t//console.log(result);\r\n");
      out.write("\t\t\t\t\t//1.解析并显示订单数据\r\n");
      out.write("\t\t\t\t\tbuild_orderGs_table(result);\r\n");
      out.write("\t\t\t\t\t//2.解析并显示分页信息\r\n");
      out.write("\t\t\t\t\tbuild_page_info(result);\r\n");
      out.write("\t\t\t\t\t//3.解析并显示分页条\r\n");
      out.write("\t\t\t\t\tbuild_page_nav(result);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction build_orderGs_table(result) {\r\n");
      out.write("\t\t\t//清空table表格\r\n");
      out.write("\t\t\t$(\"#orderGs_table tbody\").empty();\r\n");
      out.write("\t\t\tvar orderGs = result.extend.pageInfo.list;\r\n");
      out.write("\t\t\t$.each(orderGs,function(index, item) {\r\n");
      out.write("\t\t\t\t//aler(item.empName);\r\n");
      out.write("\t\t\t\tvar checkBoxTd = $(\"<td><input type='checkbox' class='check_item'/></td>\");\r\n");
      out.write("\t\t\t\tvar ordId = $(\"<td></td>\").append(item.ordId);\r\n");
      out.write("\t\t\t\tvar date = $(\"<td></td>\").append(item.date);\r\n");
      out.write("\t\t\t\tvar rname = $(\"<td></td>\").append(item.rname);\r\n");
      out.write("\t\t\t\tvar rphone = $(\"<td></td>\").append(item.rphone);\r\n");
      out.write("\t\t\t\tvar raddress = $(\"<td></td>\").append(item.raddress);\r\n");
      out.write("\t\t\t\tvar sname = $(\"<td></td>\").append(item.sname);\r\n");
      out.write("\t\t\t\tvar sphone = $(\"<td></td>\").append(item.sphone);\r\n");
      out.write("\t\t\t\tvar saddress = $(\"<td></td>\").append(item.saddress);\r\n");
      out.write("\t\t\t\tvar remark = $(\"<td></td>\").append(item.remark);\r\n");
      out.write("\t\t\t\t//append方法执行完成以后还是返回原来的元素\r\n");
      out.write("\t\t\t\t$(\"<tr></tr>\").append(checkBoxTd).append(ordId).append(date).append(rname)\r\n");
      out.write("\t\t\t\t\t\t.append(rphone).append(raddress).append(sname).append(sphone)\r\n");
      out.write("\t\t\t\t\t\t.append(saddress).append(remark).appendTo(\"#orderGs_table tbody\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//解析显示分页信息\r\n");
      out.write("\t\tfunction build_page_info(result) {\r\n");
      out.write("\t\t\t$(\"#page_info_area\").empty();\r\n");
      out.write("\t\t\t$(\"#page_info_area\").append(\r\n");
      out.write("\t\t\t\t\t\"当前\" + result.extend.pageInfo.pageNum + \"页，共\"\r\n");
      out.write("\t\t\t\t\t\t\t+ result.extend.pageInfo.pages + \"页,总\"\r\n");
      out.write("\t\t\t\t\t\t\t+ result.extend.pageInfo.total + \"条记录数\");\r\n");
      out.write("\t\t\ttotalRecord = result.extend.pageInfo.total;\r\n");
      out.write("\t\t\tcurrentPage = result.extend.pageInfo.pageNum;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//解析显示分页条，点击分页要能去下一页....\r\n");
      out.write("\t\tfunction build_page_nav(result) {\r\n");
      out.write("\t\t\t//page_nav_area\r\n");
      out.write("\t\t\t$(\"#page_nav_area\").empty();\r\n");
      out.write("\t\t\tvar ul = $(\"<ul></ul>\").addClass(\"pagination\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t//构建元素\r\n");
      out.write("\t\t\tvar firstPageLi = $(\"<li></li>\").append(\r\n");
      out.write("\t\t\t\t\t$(\"<a></a>\").append(\"首页\").attr(\"href\", \"#\"));\r\n");
      out.write("\t\t\tvar prePageLi = $(\"<li></li>\").append(\r\n");
      out.write("\t\t\t\t\t$(\"<a></a>\").append(\"&laquo;\"));\r\n");
      out.write("\t\t\tif (result.extend.pageInfo.hasPreviousPage == false) {\r\n");
      out.write("\t\t\t\tfirstPageLi.addClass(\"disabled\");\r\n");
      out.write("\t\t\t\tprePageLi.addClass(\"disabled\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t//为元素添加点击翻页的事件\r\n");
      out.write("\t\t\t\tfirstPageLi.click(function() {\r\n");
      out.write("\t\t\t\t\tto_page(1);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tprePageLi.click(function() {\r\n");
      out.write("\t\t\t\t\tto_page(result.extend.pageInfo.pageNum - 1);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar nextPageLi = $(\"<li></li>\").append(\r\n");
      out.write("\t\t\t\t\t$(\"<a></a>\").append(\"&raquo;\"));\r\n");
      out.write("\t\t\tvar lastPageLi = $(\"<li></li>\").append(\r\n");
      out.write("\t\t\t\t\t$(\"<a></a>\").append(\"末页\").attr(\"href\", \"#\"));\r\n");
      out.write("\t\t\tif (result.extend.pageInfo.hasNextPage == false) {\r\n");
      out.write("\t\t\t\tnextPageLi.addClass(\"disabled\");\r\n");
      out.write("\t\t\t\tlastPageLi.addClass(\"disabled\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tnextPageLi.click(function() {\r\n");
      out.write("\t\t\t\t\tto_page(result.extend.pageInfo.pageNum + 1);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tlastPageLi.click(function() {\r\n");
      out.write("\t\t\t\t\tto_page(result.extend.pageInfo.pages);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t//添加首页和前一页的提示\r\n");
      out.write("\t\t\tul.append(firstPageLi).append(prePageLi);\r\n");
      out.write("\t\t\t//1,2,3遍历给ul中添加页码提示\r\n");
      out.write("\t\t\t$.each(result.extend.pageInfo.navigatepageNums, function(index,\r\n");
      out.write("\t\t\t\t\titem) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar numLi = $(\"<li></li>\").append($(\"<a></a>\").append(item));\r\n");
      out.write("\t\t\t\tif (result.extend.pageInfo.pageNum == item) {\r\n");
      out.write("\t\t\t\t\tnumLi.addClass(\"active\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tnumLi.click(function() {\r\n");
      out.write("\t\t\t\t\tto_page(item);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tul.append(numLi);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//添加下一页和末页 的提示\r\n");
      out.write("\t\t\tul.append(nextPageLi).append(lastPageLi);\r\n");
      out.write("\r\n");
      out.write("\t\t\t//把ul加入到nav\r\n");
      out.write("\t\t\tvar navEle = $(\"<nav></nav>\").append(ul);\r\n");
      out.write("\t\t\tnavEle.appendTo(\"#page_nav_area\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//清空表单样式及内容\r\n");
      out.write("\t\tfunction reset_form(ele) {\r\n");
      out.write("\t\t\t$(ele)[0].reset();\r\n");
      out.write("\t\t\t//清空表单样式\r\n");
      out.write("\t\t\t$(ele).find(\"*\").removeClass(\"has-error has-success\");\r\n");
      out.write("\t\t\t$(ele).find(\".help-block\").text(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
